version: 2
sources:
  - name: ecommerce
    meta:
      external_location: "{{ env_var('TRANSFORM_S3_PATH_INPUT') }}"
    tables:
      - name: distribution_centers
      - name: events
      - name: inventory_items
      - name: orders_items
      - name: orders
      - name: products
      - name: users